services:
  app:
    container_name: flexform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    tty: true